flowchart TB
  Presentation[Angular Components]
  Logic[Services]
  Protection[Guards/Interceptors]
  Data[Models/DTOs]
  subgraph Cloud[BackendLayers]
    Controller[Controladores]
    Services[Servicios] 
    Repositories[Repositorios]
    Entities[Entidades]
  end
    DB[(MySQL / DB)]
  Presentation --> Logic --> Protection --> Data --> Controller --> Services --> Repositories --> Entities --> DB
